# Generated by Django 3.1 on 2020-08-10 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='disposable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('student_status', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('id_no', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('K', 'Female')], max_length=5)),
                ('birth_place', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('blood_type', models.CharField(choices=[('0-', '0-'), ('0+', '0+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('address', models.TextField()),
                ('area', models.CharField(choices=[('gazimağusa', 'Gazimağusa'), ('güzelyurt', 'Güzelyurt'), ('girne', 'Girne'), ('lefkoşa', 'Lefkoşa'), ('lefke', 'Lefke')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('home_phone_number', models.CharField(max_length=15)),
                ('general_information', models.TextField()),
                ('medical_information', models.TextField()),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2020, 8, 10, 11, 10, 48, 355338, tzinfo=utc))),
                ('foreign_language', models.CharField(max_length=15)),
                ('registration_type', models.CharField(choices=[('internet', 'Internet'), ('email', 'Email'), ('telephone', 'Telephone')], max_length=10)),
                ('previous_school', models.CharField(max_length=30)),
                ('scholarship', models.CharField(choices=[('0', '0'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], max_length=10)),
                ('sibling_discount', models.BooleanField()),
                ('password', models.CharField(max_length=20)),
                ('parents_marital_status', models.CharField(choices=[('together', 'Together'), ('divorced', 'Divorced')], max_length=10)),
                ('is_dad_married', models.BooleanField()),
                ('is_mother_married', models.BooleanField()),
                ('mother_state', models.CharField(choices=[('alive', 'Alive'), ('deceased', 'Deceased')], max_length=10)),
                ('dad_state', models.CharField(choices=[('alive', 'Alive'), ('deceased', 'Deceased')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_transportation', models.BooleanField()),
                ('which_way', models.CharField(choices=[('to school', 'To School'), ('fromschool', 'From School'), ('both ways', 'Both Ways')], max_length=15)),
                ('pick_up_area', models.CharField(choices=[('gazimağusa', 'Gazimağusa'), ('güzelyurt', 'Güzelyurt'), ('girne', 'Girne'), ('lefkoşa', 'Lefkoşa'), ('lefke', 'Lefke')], max_length=20)),
                ('pick_up_address', models.TextField()),
                ('drop_off_area', models.CharField(choices=[('gazimağusa', 'Gazimağusa'), ('güzelyurt', 'Güzelyurt'), ('girne', 'Girne'), ('lefkoşa', 'Lefkoşa'), ('lefke', 'Lefke')], max_length=20)),
                ('drop_off_address', models.TextField()),
                ('related_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preregistration.student')),
            ],
        ),
        migrations.CreateModel(
            name='siblings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('registered_school', models.CharField(choices=[('none', 'None'), ('neu primary', 'Near East Primary School'), ('neu college', 'Near East College'), ('other', 'Other')], max_length=20)),
                ('related_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preregistration.student')),
            ],
        ),
        migrations.CreateModel(
            name='pickup_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('relation', models.CharField(max_length=15)),
                ('related_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preregistration.student')),
            ],
        ),
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('relation', models.CharField(choices=[('mom', 'Mom'), ('dad', 'Dad'), ('sibling', 'Sibling')], max_length=8)),
                ('id_no', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('is_guardian', models.BooleanField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('home_phone_number', models.CharField(max_length=15)),
                ('work_phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('job', models.CharField(max_length=40)),
                ('workplace_name', models.CharField(max_length=40)),
                ('education_status', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('university', 'University'), ('none', 'None')], max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('related_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preregistration.student')),
            ],
        ),
    ]
