# Generated by Django 3.0.8 on 2020-07-28 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('kimlik_no', models.CharField(max_length=20)),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın'), ('D', 'Diğer')], max_length=5)),
                ('doğum_yeri', models.CharField(max_length=15)),
                ('doğum_tarihi', models.DateField()),
                ('uyruk', models.CharField(max_length=20)),
                ('kan_grubu', models.CharField(choices=[('0-', '0-'), ('0+', '0+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('adres', models.TextField()),
                ('bölge', models.CharField(max_length=20)),
                ('cep_tel', models.CharField(max_length=15)),
                ('ev_tel', models.CharField(max_length=15)),
                ('genel_bilgi', models.TextField()),
                ('sağlik_bilgisi', models.TextField()),
                ('kayıt_tarihi', models.DateTimeField(default=datetime.datetime(2020, 7, 28, 13, 34, 22, 241471, tzinfo=utc))),
                ('yabancı_dil', models.CharField(max_length=15)),
                ('kayıt_kabul', models.CharField(choices=[('Internet', 'İnternet'), ('Email', 'Email')], max_length=10)),
                ('onceki_okul', models.CharField(max_length=30)),
                ('burs', models.CharField(max_length=10)),
                ('kullanıcı', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ogrencibilgileri',
        ),
    ]
