# Generated by Django 3.0.9 on 2020-08-04 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0002_auto_20200728_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogrenci',
            options={'verbose_name_plural': 'öğrenciler'},
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='sağlik_bilgisi',
            new_name='sağlık_bilgisi',
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='kayıt_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 7, 0, 53, 776964, tzinfo=utc)),
        ),
    ]
