# Generated by Django 3.1 on 2020-08-11 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0002_auto_20200810_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposable',
            name='email',
            field=models.EmailField(default='idk@dummy.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 6, 18, 38, 813019, tzinfo=utc)),
        ),
    ]
