# Generated by Django 3.0.9 on 2020-08-05 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preregistration', '0003_auto_20200804_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('id_no', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('K', 'Female'), ('O', 'Other')], max_length=5)),
                ('birth_place', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('blood_type', models.CharField(choices=[('0-', '0-'), ('0+', '0+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('adress', models.TextField()),
                ('area', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('home_phone_number', models.CharField(max_length=15)),
                ('general_information', models.TextField()),
                ('medical_information', models.TextField()),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2020, 8, 5, 10, 15, 54, 992313, tzinfo=utc))),
                ('foreign_language', models.CharField(max_length=15)),
                ('registration_type', models.CharField(choices=[('internet', 'Internet'), ('email', 'Email'), ('telephone', 'Telephone')], max_length=10)),
                ('previous_school', models.CharField(max_length=30)),
                ('scholarship', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ogrenci',
        ),
    ]
