# Generated by Django 3.0.9 on 2020-08-05 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0004_auto_20200805_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 12, 24, 44, 559894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.CharField(choices=[('0', '0'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], max_length=10),
        ),
    ]
