# Generated by Django 3.1 on 2020-08-12 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0006_auto_20200812_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposable_transportation',
            name='related',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='preregistration.disposable'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 11, 4, 9, 684269, tzinfo=utc)),
        ),
    ]
