# Generated by Django 3.1 on 2020-08-13 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0007_auto_20200812_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 12, 3, 48, 120634, tzinfo=utc)),
        ),
    ]
