# Generated by Django 3.1 on 2020-08-13 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0008_auto_20200813_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parents',
            new_name='parent',
        ),
        migrations.RenameModel(
            old_name='siblings',
            new_name='sibling',
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 12, 6, 40, 466690, tzinfo=utc)),
        ),
    ]
