# Generated by Django 3.1 on 2020-08-14 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0009_auto_20200813_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='dummy@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 5, 45, 51, 643461, tzinfo=utc)),
        ),
    ]
