# Generated by Django 3.1 on 2020-08-25 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0013_auto_20200824_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sibling',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 6, 4, 56, 841125, tzinfo=utc)),
        ),
    ]
